# coding: utf-8
#
# Copyright © Lyra Network.
# This file is part of PayZen plugin for Odoo. See COPYING.md for license details.
#
# Author:    Lyra Network (https://www.lyra.com)
# Copyright: Copyright © Lyra Network
# License:   http://www.gnu.org/licenses/agpl.html GNU Affero General Public License (AGPL v3)

from odoo import _

# WARN: Do not modify code format here. This is managed by build files.
PAYZEN_PLUGIN_FEATURES = {
    'multi': True,
    'restrictmulti': False,
    'qualif': False,
    'shatwo': True,
}

PAYZEN_PARAMS = {
    'GATEWAY_CODE': 'PayZen',
    'GATEWAY_NAME': 'PayZen',
    'BACKOFFICE_NAME': 'PayZen',
    'SUPPORT_EMAIL': 'support@payzen.eu',
    'GATEWAY_URL': 'https://secure.payzen.eu/vads-payment/',
    'SITE_ID': '12345678',
    'KEY_TEST': '1111111111111111',
    'KEY_PROD': '2222222222222222',
    'CTX_MODE': 'TEST',
    'SIGN_ALGO': 'SHA-256',
    'LANGUAGE': 'fr',

    'GATEWAY_VERSION': 'V2',
    'PLUGIN_VERSION': '1.2.1',
    'CMS_IDENTIFIER': 'Odoo_10-14',
}

PAYZEN_LANGUAGES = {
    'cn': 'Chinese',
    'de': 'German',
    'es': 'Spanish',
    'en': 'English',
    'fr': 'French',
    'it': 'Italian',
    'jp': 'Japanese',
    'nl': 'Dutch',
    'pl': 'Polish',
    'pt': 'Portuguese',
    'ru': 'Russian',
    'sv': 'Swedish',
    'tr': 'Turkish',
}

PAYZEN_CARDS = {
    'CB': u'CB',
    'E-CARTEBLEUE': u'e-Carte Bleue',
    'MAESTRO': u'Maestro',
    'MASTERCARD': u'Mastercard',
    'VISA': u'Visa',
    'VISA_ELECTRON': u'Visa Electron',
    'VPAY': u'V PAY',
    'AMEX': u'American Express',
    'ACCORD_STORE': u'Cartes Enseignes Partenaires',
    'ACCORD_STORE_SB': u'Cartes Enseignes Partenaires (sandbox)',
    'ALINEA_CDX': u'Carte Cadeau Alinéa',
    'ALINEA_CDX_SB': u'Carte Cadeau Alinéa (sandbox)',
    'ALIPAY': u'Alipay',
    'ALLOBEBE_CDX': u'Carte Cadeau Allobébé',
    'ALLOBEBE_CDX_SB': u'Carte Cadeau Allobébé (sandbox)',
    'APETIZ': u'Apetiz',
    'AUCHAN': u'Carte Auchan',
    'AUCHAN_SB': u'Carte Auchan (sandbox)',
    'AURORE-MULTI': u'Cpay Aurore',
    'BANCONTACT': u'Bancontact Mistercash',
    'BIZZBEE_CDX': u'Carte Cadeau Bizzbee',
    'BIZZBEE_CDX_SB': u'Carte Cadeau Bizzbee (sandbox)',
    'BOULANGER': u'Carte b+',
    'BOULANGER_SB': u'Carte b+ (sandbox)',
    'BRICE_CDX': u'Carte Cadeau Brice',
    'BRICE_CDX_SB': u'Carte Cadeau Brice (sandbox)',
    'BUT': u'But',
    'CABAL': u'Cabal',
    'CARNET': u'Carnet',
    'CA_DO_CARTE': u'CA DO Carte',
    'CHQ_DEJ': u'Chèque Déjeuner',
    'CONECS': u'Conecs',
    'CONFORAMA': u'Conforama',
    'CORA': u'Cora',
    'CORA_BLANCHE': u'Cora blanche',
    'CORA_PREM': u'Cora Visa Premier',
    'CORA_VISA': u'Cora Visa',
    'CVCO': u'Chèque-Vacances Connect',
    'DINERS': u'Diners',
    'DISCOVER': u'Discover',
    'ECCARD': u'EC Card',
    'EDENRED': u'Ticket Restaurant',
    'EDENRED_EC': u'Ticket EcoCheque',
    'EDENRED_SC': u'Ticket Sport & Culture',
    'EDENRED_TC': u'Ticket Compliments',
    'EDENRED_TR': u'Ticket Restaurant',
    'ELO': u'Elo',
    'E_CV': u'e-Chèque-Vacances',
    'FRANFINANCE_3X': u'Paiement en 3 fois',
    'FRANFINANCE_4X': u'Paiement en 4 fois',
    'FULLCB3X': u'Paiement en 3 fois CB',
    'FULLCB4X': u'Paiement en 4 fois CB',
    'GEMO_CDX': u'Carte Cadeau Gémo',
    'GEMO_CDX_SB': u'Carte Cadeau Gémo (sandbox)',
    'GIROPAY': u'Giropay',
    'GOOGLEPAY': u'Google Pay',
    'HIPER': u'Hiper',
    'HIPERCARD': u'Hipercard',
    'IDEAL': u'iDEAL',
    'JCB': u'JCB',
    'JOUECLUB_CDX': u'Carte Cadeau Joué Club',
    'JOUECLUB_CDX_SB': u'Carte Cadeau Joué Club (sandbox)',
    'JULES_CDX': u'Carte Cadeau Jules',
    'JULES_CDX_SB': u'Carte Cadeau Jules (sandbox)',
    'KLARNA': u'Klarna',
    'LECLERC': u'Carte Reglo',
    'MC_CORDOBESA': u'Mastercard Cordobesa',
    'MULTIBANCO': u'Multibanco',
    'MYBANK': u'MyBank',
    'NARANJA': u'Naranja',
    'NORAUTO': u'Carte Norauto option Financement',
    'NORAUTO_SB': u'Carte Norauto option Financement (sandbox)',
    'ONEY_3X_4X': u'Paiement en 3 ou 4 fois Oney',
    'ONEY_ENSEIGNE': u'Cartes enseignes Oney',
    'PAYDIREKT': u'Paydirekt',
    'PAYLIB': u'Paylib',
    'PAYPAL': u'PayPal',
    'PAYPAL_SB': u'PayPal Sandbox',
    'PICWIC': u'Carte Picwic',
    'PICWIC_SB': u'Carte Picwic (sandbox)',
    'POSTFINANCE': u'PostFinance Card',
    'POSTFINANCE_EFIN': u'PostFinance E-Finance',
    'PRESTO': u'Presto',
    'PRZELEWY24': u'Przelewy24',
    'S-MONEY': u'S-money',
    'SCT': u'Virement SEPA',
    'SDD': u'Prélèvement SEPA',
    'SODEXO': u'Pass Restaurant',
    'SOFORT_BANKING': u'Sofort',
    'SOROCRED': u'Sorocred',
    'TRUFFAUT_CDX': u'Carte Cadeau Truffaut',
    'UNION_PAY': u'UnionPay',
    'WECHAT': u'WeChat Pay',
}

PAYZEN_CURRENCIES = [
    ['AUD', '036', 2],
    ['KHR', '116', 0],
    ['CAD', '124', 2],
    ['CNY', '156', 1],
    ['CZK', '203', 2],
    ['DKK', '208', 2],
    ['HKD', '344', 2],
    ['HUF', '348', 2],
    ['INR', '356', 2],
    ['IDR', '360', 2],
    ['JPY', '392', 0],
    ['KRW', '410', 0],
    ['KWD', '414', 3],
    ['MYR', '458', 2],
    ['MXN', '484', 2],
    ['MAD', '504', 2],
    ['NZD', '554', 2],
    ['NOK', '578', 2],
    ['PHP', '608', 2],
    ['RUB', '643', 2],
    ['SGD', '702', 2],
    ['ZAR', '710', 2],
    ['SEK', '752', 2],
    ['CHF', '756', 2],
    ['THB', '764', 2],
    ['TND', '788', 3],
    ['GBP', '826', 2],
    ['USD', '840', 2],
    ['TWD', '901', 2],
    ['TRY', '949', 2],
    ['EUR', '978', 2],
    ['PLN', '985', 2],
    ['BRL', '986', 2],
    ['ARS', '032', 2],
    ['COP', '170', 2],
    ['PEN', '604', 2],
]