# coding: utf-8
#
# Copyright © Lyra Network.
# This file is part of PayZen plugin for Odoo. See COPYING.md for license details.
#
# Author:    Lyra Network (https://www.lyra.com)
# Copyright: Copyright © Lyra Network
# License:   http://www.gnu.org/licenses/agpl.html GNU Affero General Public License (AGPL v3)

from odoo import _

# WARN: Do not modify code format here. This is managed by build files.
PAYZEN_PLUGIN_FEATURES = {
    'multi': True,
    'restrictmulti': False,
    'qualif': False,
    'shatwo': True,
}

PAYZEN_PARAMS = {
    'GATEWAY_CODE': 'PayZen',
    'GATEWAY_NAME': 'PayZen',
    'BACKOFFICE_NAME': 'PayZen',
    'SUPPORT_EMAIL': 'support@payzen.eu',
    'GATEWAY_URL': 'https://secure.payzen.eu/vads-payment/',
    'SITE_ID': '12345678',
    'KEY_TEST': '1111111111111111',
    'KEY_PROD': '2222222222222222',
    'CTX_MODE': 'TEST',
    'SIGN_ALGO': 'SHA-256',
    'LANGUAGE': 'fr',

    'GATEWAY_VERSION': 'V2',
    'PLUGIN_VERSION': '3.0.3',
    'CMS_IDENTIFIER': 'Odoo_16',
}

PAYZEN_LANGUAGES = {
    'cn': 'Chinese',
    'de': 'German',
    'es': 'Spanish',
    'en': 'English',
    'fr': 'French',
    'it': 'Italian',
    'jp': 'Japanese',
    'nl': 'Dutch',
    'pl': 'Polish',
    'pt': 'Portuguese',
    'ru': 'Russian',
    'sv': 'Swedish',
    'tr': 'Turkish',
}

PAYZEN_CARDS = {
            'CB': u'CB',
    'E-CARTEBLEUE': u'e-Carte Bleue',
    'MAESTRO': u'Maestro',
    'MASTERCARD': u'Mastercard',
            'VISA': u'Visa',
    'VISA_ELECTRON': u'Visa Electron',
    'VPAY': u'V PAY',
    'AMEX': u'American Express',
            'ACCORD_STORE': u'Cartes Enseignes Partenaires',
    'ACCORD_STORE_SB': u'Cartes Enseignes Partenaires (sandbox)',
            'ALINEA': u'Carte myalinea',
    'ALINEA_CDX': u'Carte Cadeau Alinéa',
    'ALINEA_CDX_SB': u'Carte Cadeau Alinéa (sandbox)',
            'ALINEA_SB': u'Carte myalinea (sandbox)',
    'ALIPAY': u'Alipay',
    'ALLOBEBE_CDX': u'Carte Cadeau Allobébé',
            'ALLOBEBE_CDX_SB': u'Carte Cadeau Allobébé (sandbox)',
    'ALMA': u'Alma en 1 fois',
    'ALMA_10X': u'Alma en 10 fois',
            'ALMA_12X': u'Alma en 12 fois',
    'ALMA_2X': u'Alma en 2 fois',
    'ALMA_3X': u'Alma en 3 fois',
            'ALMA_4X': u'Alma en 4 fois',
    'APETIZ': u'Apetiz',
    'APPLE_PAY': u'Apple Pay',
            'AUCHAN': u'Carte Auchan',
    'AUCHAN_SB': u'Carte Auchan (sandbox)',
    'AURORE-MULTI': u'Cpay Aurore',
            'BANCONTACT': u'Bancontact Mistercash',
    'BIZUM': u'Bizum',
    'BIZZBEE_CDX': u'Carte Cadeau Bizzbee',
            'BIZZBEE_CDX_SB': u'Carte Cadeau Bizzbee (sandbox)',
    'BOULANGER': u'Carte b+',
            'BOULANGER_SB': u'Carte b+ (sandbox)',
    'BRICE_CDX': u'Carte Cadeau Brice',
    'BRICE_CDX_SB': u'Carte Cadeau Brice (sandbox)',
            'BUT': u'But',
    'CABAL': u'Cabal',
    'CARNET': u'Carnet',
    'CASINO': u'Banque Casino',
    'CA_DO_CARTE': u'CA DO Carte',
            'CDGP': u'Carte Privilège',
    'CDISCOUNT': u'CDiscount',
    'CHQ_DEJ': u'Chèque Déjeuner',
    'COF3XCB': u'Cofinoga 3 fois CB',
            'COF3XCB_SB': u'Cofinoga 3 fois CB Sandbox',
    'COFINOGA': u'Cofinoga',
    'COM_BARRY_CDX': u'Carte Cadeau Comtesse du Barry',
            'COM_BARRY_CDX_SB': u'Carte Cadeau Comtesse du Barry (sandbox)',
    'CONECS': u'Conecs',
    'CONFORAMA': u'Conforama',
            'CORA': u'Cora',
    'CORA_BLANCHE': u'Cora blanche',
    'CORA_PREM': u'Cora Visa Premier',
    'CORA_VISA': u'Cora Visa',
            'CVCO': u'Chèque-Vacances Connect',
    'DINERS': u'Diners',
    'DISCOVER': u'Discover',
    'ECCARD': u'EC Card',
            'EDENRED': u'Ticket Restaurant',
    'EDENRED_EC': u'Ticket EcoCheque',
    'EDENRED_SC': u'Ticket Sport & Culture',
            'EDENRED_TC': u'Ticket Compliments',
    'EDENRED_TR': u'Ticket Restaurant',
    'ELO': u'Elo',
    'ELV': u'ELV',
            'FRANFINANCE_3X': u'Paiement en 3 fois',
    'FRANFINANCE_4X': u'Paiement en 4 fois',
    'FULLCB3X': u'Paiement en 3 fois CB',
            'FULLCB4X': u'Paiement en 4 fois CB',
    'GEMO_CDX': u'Carte Cadeau Gémo',
    'GEMO_CDX_SB': u'Carte Cadeau Gémo (sandbox)',
            'GIROPAY': u'Giropay',
    'HIPER': u'Hiper',
    'HIPERCARD': u'Hipercard',
    'IDEAL': u'iDEAL',
            'ILLICADO': u'Carte Illicado',
    'ILLICADO_SB': u'Carte Illicado (sandbox)',
    'IP_WIRE': u'Virement SEPA',
            'IP_WIRE_INST': u'Virement SEPA Instantané',
    'JCB': u'JCB',
    'JOUECLUB_CDX': u'Carte Cadeau Joué Club',
            'JOUECLUB_CDX_SB': u'Carte Cadeau Joué Club (sandbox)',
    'JULES_CDX': u'Carte Cadeau Jules',
            'JULES_CDX_SB': u'Carte Cadeau Jules (sandbox)',
    'KADEOS_CULTURE': u'Carte Kadéos Culture',
            'KADEOS_GIFT': u'Carte Kadéos Zénith',
    'KLARNA': u'Klarna',
    'LECLERC': u'Carte Reglo',
            'LEROY-MERLIN': u'Carte Maison Financement',
    'LEROY-MERLIN_SB': u'Carte Maison Financement (sandbox)',
            'MASTERPASS': u'MasterPass',
    'MC_CORDOBESA': u'Mastercard Cordobesa',
    'MULTIBANCO': u'Multibanco',
    'MYBANK': u'MyBank',
            'NARANJA': u'Naranja',
    'NORAUTO': u'Carte Norauto option Financement',
    'NORAUTO_SB': u'Carte Norauto option Financement (sandbox)',
            'ONEY': u'Paiement en 3 ou 4 fois par CB',
    'ONEY_10X_12X': u'Paiement en 10 ou 12 fois Oney',
            'ONEY_3X_4X': u'Paiement en 3 ou 4 fois Oney',
    'ONEY_ENSEIGNE': u'Cartes enseignes Oney',
    'ONEY_PAYLATER': u'Pay Later Oney',
            'ONEY_SANDBOX': u'Paiement en 3 ou 4 fois par CB (sandbox)',
    'PAYBOX': u'Paybox',
    'PAYDIREKT': u'Paydirekt',
    'PAYPAL': u'PayPal',
            'PAYPAL_SB': u'PayPal Sandbox',
    'PICWIC': u'Carte Picwic',
    'PICWIC_SB': u'Carte Picwic (sandbox)',
            'POSTFINANCE': u'PostFinance Card',
    'POSTFINANCE_EFIN': u'PostFinance E-Finance',
    'PRESTO': u'Presto',
            'PRZELEWY24': u'Przelewy24',
    'S-MONEY': u'S-money',
    'SCT': u'Virement SEPA',
    'SDD': u'Prélèvement SEPA',
            'SODEXO': u'Pass Restaurant',
    'SOFICARTE': u'Soficarte',
    'SOFORT_BANKING': u'Sofort',
    'SOROCRED': u'Sorocred',
            'SYGMA': u'Sygma',
    'TRUFFAUT_CDX': u'Carte Cadeau Truffaut',
    'UNION_PAY': u'UnionPay',
    'VILLAVERDE': u'Carte Cadeau VillaVerde',
            'VILLAVERDE_SB': u'Carte Cadeau VillaVerde (sandbox)',
    'WECHAT': u'WeChat Pay',
}

PAYZEN_CURRENCIES = [
            ['ARS', '032', 2],
    ['AUD', '036', 2],
    ['BRL', '986', 2],
    ['CAD', '124', 2],
            ['CHF', '756', 2],
    ['CNY', '156', 2],
    ['COP', '170', 2],
    ['CZK', '203', 2],
            ['DKK', '208', 2],
    ['EUR', '978', 2],
    ['GBP', '826', 2],
    ['HKD', '344', 2],
            ['HUF', '348', 2],
    ['IDR', '360', 0],
    ['INR', '356', 2],
    ['JPY', '392', 0],
            ['KHR', '116', 0],
    ['KRW', '410', 0],
    ['KWD', '414', 3],
    ['MAD', '504', 2],
            ['MXN', '484', 2],
    ['MYR', '458', 2],
    ['NOK', '578', 2],
    ['NZD', '554', 2],
            ['PEN', '604', 2],
    ['PHP', '608', 2],
    ['PLN', '985', 2],
    ['RUB', '643', 2],
            ['SEK', '752', 2],
    ['SGD', '702', 2],
    ['THB', '764', 2],
    ['TND', '788', 3],
            ['TRY', '949', 2],
    ['TWD', '901', 2],
    ['USD', '840', 2],
    ['XOF', '952', 0],
            ['XPF', '953', 0],
    ['ZAR', '710', 2],
]

PAYZEN_ONLINE_DOC_URI = {
            'fr': 'https://payzen.io/fr-FR/plugins/',
            'en': 'https://payzen.io/en-EN/plugins/',
            'es': 'https://payzen.io/es-ES/plugins/',
}

PAYZEN_DOCUMENTATION = {
    'fr': 'Français',
    'en': 'English',
    'es': 'Español',
    'de': 'Deutsch',
    'pt': 'Português',
}